- name: test file touch
  #gather_facts: no
  hosts: all
  #serial: 1
  #  vars_files:
  #  - vars/vars.yml
  tasks:
    - name: Create Directory
      file:
        path: /home/ansibletower/mytest112233
        state: directory
#        owner: appuser
#        group: appuser
        owner : user
        group : user
