- name: test file touch
  #gather_facts: no
  hosts: myhost
  #serial: 1
  #  vars_files:
  #  - vars/vars.yml
  tasks:
    - name: Create Directory
      become: true
      become_user: production1
      file:
        path: /home/production1/mytest112233
        state: directory
        owner: production1
        group: production1
