- name: test file touch
  #gather_facts: no
  hosts: myhost
  #serial: 1
  #  vars_files:
  #  - vars/vars.yml
  tasks:
    - name: Create Directory
      become: true
      become_user: parekh
      file:
        path: /home/ansibletower/mytest112233
        state: directory
        owner: parekh
